name: Generate Cause List

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install -r requirements.txt

      - run: python main.py

      - uses: actions/upload-artifact@v4
        with:
          name: CauseList
          path: Consolidated_Cause_List.pdf
